NUMBER_OF_QUESTIONS_BY_CATEGORY= 50
LIST_OF_CATEGORIES= ['Pop', 'Science', 'Sports', 'Rock']
MIN_NUMBER_OF_PLAYERS= 2
POINT_FOR_WINNING= 6
DICE_FACE= 6
NUMBER_OF_PLACES = 12


dict_places_category = {
    (0,4,8): LIST_OF_CATEGORIES[0],
    (1,5,9): LIST_OF_CATEGORIES[1],
    (2,6,10): LIST_OF_CATEGORIES[2],
    (3,7,11): LIST_OF_CATEGORIES[3],
}