NUMBER_OF_QUESTIONS_BY_CATEGORY= 50
CATEGORY_1 = 'Pop'
CATEGORY_2 = 'Science'
CATEGORY_3 = 'Sports'
CATEGORY_4 = 'Rock'
LIST_OF_CATEGORIES= [CATEGORY_1, CATEGORY_2, CATEGORY_3, CATEGORY_4]
MIN_NUMBER_OF_PLAYERS= 2
POINT_FOR_WINNING= 6
DICE_FACE= 6
NUMBER_OF_PLACES = 12

dict_places_category = {
    (0,4,8): CATEGORY_1,
    (1,5,9): CATEGORY_2,
    (2,6,10): CATEGORY_3,
    (3,7,11): CATEGORY_4,
}